---
# yamllint disable rule:line-length
name: "Tests"

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run
        uses: "./"
        with:
          irc-server: "irc.hackint.org"
          irc-nickname: "workflow-test"
          irc-target: "#ffda-github-irc"
          message: "${{ github.head_ref }} ${{ github.sha }}"
